// <auto-generated />
using CS2_GEO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CS2_GEO.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260922151554_AddMapSizeUnits")]
    partial class AddMapSizeUnits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CS2_GEO.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("map_id");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("MapId")
                        .HasDatabaseName("ix_locations_map_id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("CS2_GEO.Data.Entities.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("MinimapUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("minimap_url");

                    b.Property<double>("SizeUnits")
                        .HasColumnType("double precision")
                        .HasColumnName("size_units");

                    b.HasKey("Id")
                        .HasName("pk_maps");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_maps_code");

                    b.ToTable("maps", (string)null);
                });

            modelBuilder.Entity("CS2_GEO.Data.Entities.Location", b =>
                {
                    b.HasOne("CS2_GEO.Data.Entities.Map", "Map")
                        .WithMany("Locations")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_locations_maps_map_id");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("CS2_GEO.Data.Entities.Map", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
